script:
    - docker build --target test --tag my-test-image .
    - docker run my-test-image tests/unit
    - docker run my-test-image tests/integration
    - docker run my-test-image tests/endtoend --env apiKey=MY_API_KEY --env apiToken=MY_API_TOKEN --env boardId=MY_BOARD_ID -env TODO_LIST_ID=MY_TODO_LIST_ID -env DOING_LIST_ID=MY_DOING_LIST_ID -env DONE_LIST_ID=MY_DONE_LIST_ID -env FLASK_APP=MY_FLASK_APP -env FLASK_ENV=MY_FLASK_ENV